{
 "title": "Linux Bluetooth",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Read/write syscalls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_pkt_call[$__interval])",
     "legendFormat": "{{proto}} - {{recv}} - ret {{errorno}}"
    }
   ]
  },
  {
   "title": "Syscalls size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_pkt_size[$__interval])",
     "legendFormat": "{{proto}} - {{recv}}"
    }
   ]
  },
  {
   "title": "Bufsize L2CAP",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bufsize_bucket{proto=\"L2CAP\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Bufsize SCO",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_bufsize_bucket{proto=\"SCO\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Hdev count - ACL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_hdev_count{type=\"ACL\"}[$__interval])",
     "legendFormat": "{{type}} - {{count}}"
    }
   ]
  },
  {
   "title": "URB Time - ACL",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_urb_time_bucket{event_type=\"ACL\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time - Number Completed Packets",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_urb_time_bucket{event_type=\"ACL ACK\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "URB Time - SCO",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "rate(ebpf_exporter_urb_time_bucket{event_type=\"SCO\"}[$__interval])",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}